server:
  port: 8080
spring:
  application:
    name: order-service
  datasource:
    username: myuser
    password: secret
    url: jdbc:postgresql://host.docker.internal:5433/mydatabase
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: "mydatabase"
      username: root
      password: secret